(require htdp/testing)

(load "interpreter.rkt")

;;Part 1
;(check-expect (interpret "tests/Part1Test1.txt") 150)
;(check-expect (interpret "tests/Part1Test2.txt") -4)
;(check-expect (interpret "tests/Part1Test3.txt") 10)
;(check-expect (interpret "tests/Part1Test4.txt") 16)
;(check-expect (interpret "tests/Part1Test5.txt") 220)
;(check-expect (interpret "tests/Part1Test6.txt") 5)
;(check-expect (interpret "tests/Part1Test7.txt") 6)
;(check-expect (interpret "tests/Part1Test8.txt") 10)
;(check-expect (interpret "tests/Part1Test9.txt") 5)
;(check-expect (interpret "tests/Part1Test10.txt") -39)
;(check-error (interpret "tests/Part1Test11.txt") "error: usingBeforeDeclaringOrOutOfScope")
;(check-error (interpret "tests/Part1Test12.txt") "error: usingBeforeDeclaringOrOutOfScope")
;(check-error (interpret "tests/Part1Test13.txt") "error: usingBeforeAssigning")
;(check-error (interpret "tests/Part1Test14.txt") "error: variableAlreadyDeclared")
;(check-expect (interpret "tests/Part1Test15.txt") 'true)
;(check-expect (interpret "tests/Part1Test16.txt") 100)
;(check-expect (interpret "tests/Part1Test17.txt") 'false)
;(check-expect (interpret "tests/Part1Test18.txt") 'true)
;; optional
;(check-expect (interpret "tests/Part1Test19.txt") 30)
;(check-expect (interpret "tests/Part1Test20.txt") 11)
;(check-expect (interpret "tests/Part1Test21.txt") 1106)
;(check-expect (interpret "tests/Part1Test22.txt") 12)
;(check-expect (interpret "tests/Part1Test23.txt") 16)
;(check-expect (interpret "tests/Part1Test24.txt") 72)
;
;;;Part 2
;(check-expect (interpret "tests/Part2Test1.txt") 100)
;(check-expect (interpret "tests/Part2Test2.txt") 20)
;(check-expect (interpret "tests/Part2Test3.txt") 6)
;(check-expect (interpret "tests/Part2Test4.txt") -1)
;(check-expect (interpret "tests/Part2Test5.txt") 789)
;(check-expect (interpret "tests/Part2Test6.txt") 2)
;(check-expect (interpret "tests/Part2Test7.txt") 164)
;(check-error (interpret "tests/Part2Test8.txt") "error: usingBeforeDeclaringOrOutOfScope")
;(check-error (interpret "tests/Part2Test9.txt") "error: usingBeforeDeclaringOrOutOfScope")
;(check-error (interpret "tests/Part2Test10.txt") "error: usingBeforeDeclaringOrOutOfScope")
;(check-expect (interpret "tests/Part2Test11.txt") 12)
;(check-expect (interpret "tests/Part2Test12.txt") 32)
;;optional
;(check-expect (interpret "tests/Part2Test13.txt") 21)
;
;;Part 3
;(check-expect (interpret "tests/test1.txt") 10)
;(check-expect (interpret "tests/test2.txt") 14)
;(check-expect (interpret "tests/test3.txt") 45)
;(check-expect (interpret "tests/test4.txt") 55) 
;(check-expect (interpret "tests/test6.txt") 115)
;(check-expect (interpret "tests/test7.txt") 'true)
;(check-expect (interpret "tests/test8.txt") 20)
;(check-expect (interpret "tests/test9.txt") 24)
;(check-error (interpret "tests/test12.txt") "error: mismatchParameters")
;(check-expect (interpret "tests/test14.txt") 69)
;(check-expect (interpret "tests/test13.txt") 90)
;(check-error (interpret "tests/test17.txt") "error: usingBeforeDeclaringOrOutOfScope")
;(check-expect (interpret "tests/test16.txt") 64)
;(check-expect (interpret "tests/test10.txt") 2) 
;(check-expect (interpret "tests/test11.txt") 35)
;(check-expect (interpret "tests/test5.txt") 1
;(check-expect (interpret "tests/test15.txt") 87) 

;Part 4
(check-expect (interpret "tests/Part4Test1.txt" "A") 10)
(check-expect (interpret "tests/Part4Test2.txt" "A") 'true)
(check-expect (interpret "tests/Part4Test3.txt" "A") 30)
(check-expect (interpret "tests/Part4Test4.txt" "A") 'false)
(check-expect (interpret "tests/Part4Test5.txt" "A") 30)
(check-expect (interpret "tests/Part4Test5.txt" "B") 510)
(check-expect (interpret "tests/Part4Test6.txt" "A") 30)
(check-expect (interpret "tests/Part4Test6.txt" "B") 530)
(check-expect (interpret "tests/Part4Test7.txt" "A") 105)
(check-expect (interpret "tests/Part4Test7.txt" "B") 1155)
(check-expect (interpret "tests/Part4Test8.txt" "B") 615)
(check-error (interpret "tests/Part4Test9.txt" "B") "error: usingBeforeDeclaringOrOutOfScope")
(check-expect (interpret "tests/Part4Test9.txt" "C") 4321)
(check-expect (interpret "tests/Part4Test10.txt" "Square") 400)
(check-expect (interpret "tests/Part4Test11.txt" "A") 15)
(check-expect (interpret "tests/Part4Test12.txt" "A") 125)
(check-expect (interpret "tests/Part4Test13.txt" "A") 100)
(check-expect (interpret "tests/Part4Test14.txt" "A") 2000400)
(check-expect (interpret "tests/Part4Test15.txt" "Pow") 64)

(check-expect (interpret "tests/Part5Test1.txt" "A") 20)
(check-expect (interpret "tests/Part5Test2.txt" "Square") 400)
(check-expect (interpret "tests/Part5Test3.txt" "B") 530)
(check-expect (interpret "tests/Part5Test4.txt" "B") 615)
(check-expect (interpret "tests/Part5Test5.txt" "C") -716) ;try catch throw stuff / infinite loop
(check-expect (interpret "tests/Part5Test6.txt" "A") 15)
(check-expect (interpret "tests/Part5Test7.txt" "A") 12)
(check-expect (interpret "tests/Part5Test8.txt" "A") 110)
(check-expect (interpret "tests/Part5Test9.txt" "A") 125)
(check-expect (interpret "tests/Part5Test10.txt" "A") 36)
(check-expect (interpret "tests/Part5Test11.txt" "A") 54)
(check-expect (interpret "tests/Part5Test12.txt" "C") 26)
;(check-expect (interpret "tests/Part5Test13.txt" "Square") 117)
;(check-expect (interpret "tests/Part5Test14.txt" "Square") 32)
;(check-expect (interpret "tests/Part5Test15.txt" "List") 15)
;(check-expect (interpret "tests/Part5Test16.txt" "Box") 16)
;(check-expect (interpret "tests/Part5Test17.txt" "List") 123456)
;(check-expect (interpret "tests/Part5Test18.txt" "List") 5285)
(check-expect (interpret "tests/Part5Test19.txt" "A") 100)
(check-expect (interpret "tests/Part5Test20.txt" "A") 420)
;(check-expect (interpret "tests/Part5Test21.txt" "A") 10)
;(check-error (interpret "tests/Part5Test22.txt" "A") "error: usingBeforeDeclaringOrOutOfScope") ;infinite loop

(generate-report)