(require htdp/testing)

(load "interpreter.rkt")

;;Part 1
;(check-expect (interpret "tests/Part1Test1.txt") 150)
;(check-expect (interpret "tests/Part1Test2.txt") -4)
;(check-expect (interpret "tests/Part1Test3.txt") 10)
;(check-expect (interpret "tests/Part1Test4.txt") 16)
;(check-expect (interpret "tests/Part1Test5.txt") 220)
;(check-expect (interpret "tests/Part1Test6.txt") 5)
;(check-expect (interpret "tests/Part1Test7.txt") 6)
;(check-expect (interpret "tests/Part1Test8.txt") 10)
;(check-expect (interpret "tests/Part1Test9.txt") 5)
;(check-expect (interpret "tests/Part1Test10.txt") -39)
;(check-error (interpret "tests/Part1Test11.txt") "error: usingBeforeDeclaring")
;(check-error (interpret "tests/Part1Test12.txt") "error: usingBeforeDeclaring")
;(check-error (interpret "tests/Part1Test13.txt") "error: usingBeforeAssigning")
;(check-error (interpret "tests/Part1Test14.txt") "error: variableAlreadyDeclared")
;(check-expect (interpret "tests/Part1Test15.txt") 'true)
;(check-expect (interpret "tests/Part1Test16.txt") 100)
;(check-expect (interpret "tests/Part1Test17.txt") 'false)
;(check-expect (interpret "tests/Part1Test18.txt") 'true)
;; optional
;(check-expect (interpret "tests/Part1Test19.txt") 30)
;(check-expect (interpret "tests/Part1Test20.txt") 11)
;(check-expect (interpret "tests/Part1Test21.txt") 1106)
;(check-expect (interpret "tests/Part1Test22.txt") 12)
;(check-expect (interpret "tests/Part1Test23.txt") 16)
;(check-expect (interpret "tests/Part1Test24.txt") 72)
;
;;Part 2
;(check-expect (interpret "tests/Part2Test1.txt") 100)
;(check-expect (interpret "tests/Part2Test2.txt") 20)
;(check-expect (interpret "tests/Part2Test3.txt") 6)
;(check-expect (interpret "tests/Part2Test4.txt") -1)
;(check-expect (interpret "tests/Part2Test5.txt") 789)
;(check-expect (interpret "tests/Part2Test6.txt") 2)
;(check-expect (interpret "tests/Part2Test7.txt") 164)
;(check-error (interpret "tests/Part2Test8.txt") "error: usingBeforeDeclaring")
;(check-error (interpret "tests/Part2Test9.txt") "error: usingBeforeDeclaring")
;(check-error (interpret "tests/Part2Test10.txt") "error: variableAlreadyDeclared")
;(check-expect (interpret "tests/Part2Test11.txt") 12)
;(check-expect (interpret "tests/Part2Test12.txt") 32)
;;optional
;(check-expect (interpret "tests/Part2Test13.txt") 21)

;Part 3
(check-expect (interpret "test1.txt") 10)
(check-expect (interpret "test2.txt") 14)
(check-expect (interpret "test3.txt") 45)
;(check-expect (interpret "test4.txt") 55) 
(check-expect (interpret "test5.txt") 1)
(check-expect (interpret "test6.txt") 115)
(check-expect (interpret "test7.txt") 'true)
(check-expect (interpret "test8.txt") 20)
(check-expect (interpret "test9.txt") 24)
;(check-expect (interpret "test10.txt") 2)
;(check-expect (interpret "test11.txt") 35)
(check-error (interpret "test12.txt") "error: mismatchParameters")
;(check-expect (interpret "test13.txt") 90)
(check-expect (interpret "test14.txt") 69)
;(check-expect (interpret "test15.txt") 87)
;(check-expect (interpret "test16.txt") 64)
;(check-error (interpret "test17.txt") "error: outOfScope")

(generate-report)
